---
- name: Copy Repo File To Remote Server
  copy:
     src: ./mariadb/files/MariaDB.repo
     dest: /etc/yum.repos.d/
     owner: root
     group: root
- name: Install boost-program-options
  yum:  
     name: boost-program-options
     state: latest
- name: Install MariaDB
  yum:
     name: MariaDB-server,MariaDB-client
     disablerepo: AppStream
     state: latest
